# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3f2f2b6113e1ecaa0de0957be646e5f937e5f577c720e4382746b56020db9e0c0fbab6bd2548446902074ad58607bc7a0e4492977d8a6850d1bbde23caaca8b

test:
  secret_key_base: e59d580611f1e94202bb8b47d0dbf82b44eede544ad782a785230a96414753be0c7b7f3edb81beb1c0c6085e9b64f7d367414a90fd6a1cfe0f3e92f527f76c5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
